### ISSUE TITLE
Note on disambiguation for line breaks by Bunkai

### ISSUE THREAD

**Issue by shirayu** [hkiyomaru/ja-senter-benchmark#1]
Hi, I  am the author of Bunkai.
Nice evaluation!

Please be aware that you need to specify a model at the following line to analyze line breaks by Bunkai as I have just noted [here](https://github.com/megagonlabs/bunkai#python-library).

https://github.com/hkiyomaru/ja-senter-benchmark/blob/9e30c39ea2262237c468c97c9f0c0f8e1d30a920/senters.py#L30

**Comment by hkiyomaru** [comment]
Thanks for pointing this out! Commit c004693bfd5fd2187c9725b66a9dccc0ad532c21 should fix this issue. I've confirmed a performance improvement in `new_line.jsonl`.
